import { NextResponse } from "next/server";
import { 
  COMPANY_NAME, 
  HERO_CONTENT, 
  CAPABILITIES, 
  SYSTEMS_PROJECTS, 
  TICKER_HEADLINES, 
  FOUNDER_CONTENT 
} from "@/app/data/content";

export async function GET() {
  const markdown = `
# ${COMPANY_NAME}

> ${HERO_CONTENT.masthead.quote}

## ${HERO_CONTENT.leadStory.label}: ${HERO_CONTENT.leadStory.title}
By ${HERO_CONTENT.leadStory.author} | ${HERO_CONTENT.leadStory.readTime}

${HERO_CONTENT.leadStory.content.join("\n\n")}

---

## ${HERO_CONTENT.sidebar.title}

${HERO_CONTENT.sidebar.items.map(item => `### ${item.title}
${item.subtitle} (Page ${item.page})`).join("\n\n")}

---

## Opinion & Analysis

${CAPABILITIES.map(cap => `### ${cap.title}: ${cap.headline}
${cap.description}`).join("\n\n")}

---

## Feature Stories (Systems)

${SYSTEMS_PROJECTS.map(project => `### ${project.title} (${project.status})
**${project.headline}**
${project.description}
Tags: ${project.tags.join(", ")}`).join("\n\n")}

---

## Latest Intel

${TICKER_HEADLINES.map(headline => `- ${headline}`).join("\n")}

---

## Founder: ${FOUNDER_CONTENT.name}
${FOUNDER_CONTENT.title}
"${FOUNDER_CONTENT.quote}"
Location: ${FOUNDER_CONTENT.location}

### Connect
${FOUNDER_CONTENT.socials.map(social => `- [${social.label}](${social.href})`).join("\n")}

---
Generated by 0xFLOW Intelligence Engine
`.trim();

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
